<a href="https://colab.research.google.com/github/OulinG138/STA313-Project/blob/main/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# run once
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Check the data and conver the timestamp

- TODO
    - Convert `Zeitstempel` to readable timestamp

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_rows', 10)  # Limits displayed rows
pd.set_option('display.max_columns', 10)  # Limits displayed columns

In [45]:
file_path = "/content/drive/MyDrive/Colab Notebooks/STA313/data/Gaming Study Data.csv"

df = pd.read_csv(file_path, encoding="ISO-8859-1", index_col=0)
df.head()

,Zeitstempel,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
1,42052.004366,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
2,42052.006803,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
3,42052.038599,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
4,42052.068037,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20.0,I play for fun,improving,NaN,NaN,5.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,Male,28,Employed,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
5,42052.089478,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,NaN,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,Male,19,Employed,High school diploma (or equivalent),USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13464 entries, 1 to 14250
Data columns (total 54 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Datetime         13464 non-null  datetime64[ns]
 1   GAD1             13464 non-null  int64
 2   GAD2             13464 non-null  int64
 3   GAD3             13464 non-null  int64
 4   GAD4             13464 non-null  int64
 5   GAD5             13464 non-null  int64
 6   GAD6             13464 non-null  int64
 7   GAD7             13464 non-null  int64
 8   GADE             12815 non-null  object
 9   SWL1             13464 non-null  int64
 10  SWL2             13464 non-null  int64
 11  SWL3             13464 non-null  int64
 12  SWL4             13464 non-null  int64
 13  SWL5             13464 non-null  int64
 14  Game             13464 non-null  object
 15  Platform         13464 non-null  object
 16  Hours            13434 non-null  float64
 17  earnings         13464 non-null  object
 18  whyplay          13464 non-null  object
 19  League           11612 non-null  object
 20  highestleague    0 non-null      float64
 21  streams          13364 non-null  float64
 22  SPIN1            13340 non-null  float64
 23  SPIN2            13310 non-null  float64
 24  SPIN3            13324 non-null  float64
 25  SPIN4            13305 non-null  float64
 26  SPIN5            13298 non-null  float64
 27  SPIN6            13308 non-null  float64
 28  SPIN7            13326 non-null  float64
 29  SPIN8            13320 non-null  float64
 30  SPIN9            13306 non-null  float64
 31  SPIN10           13304 non-null  float64
 32  SPIN11           13277 non-null  float64
 33  SPIN12           13296 non-null  float64
 34  SPIN13           13277 non-null  float64
 35  SPIN14           13308 non-null  float64
 36  SPIN15           13317 non-null  float64
 37  SPIN16           13317 non-null  float64
 38  SPIN17           13289 non-null  float64
 39  Narcissism       13441 non-null  float64
 40  Gender           13464 non-null  object
 41  Age              13464 non-null  int64
 42  Work             13426 non-null  object
 43  Degree           11887 non-null  object
 44  Birthplace       13464 non-null  object
 45  Residence        13464 non-null  object
 46  Reference        13449 non-null  object
 47  Playstyle        13464 non-null  object
 48  accept           13050 non-null  object
 49  GAD_T            13464 non-null  int64
 50  SWL_T            13464 non-null  int64
 51  SPIN_T           12814 non-null  float64
 52  Residence_ISO3   13354 non-null  object
 53  Birthplace_ISO3  13343 non-null  object
dtypes: datetime64[ns](1), float64(22), int64(15), object(16)
memory usage: 5.6+ MB

In [ ]:
df.describe()

,Datetime,GAD1,GAD2,GAD3,GAD4,...,Narcissism,Age,GAD_T,SWL_T,SPIN_T
count,13464,13464.000000,13464.000000,13464.000000,13464.000000,...,13441.000000,13464.000000,13464.000000,13464.000000,12814.000000
mean,2017-02-20 20:11:21.060680192,0.860963,0.673351,0.965761,0.724079,...,2.027677,20.930407,5.211973,19.788844,19.848525
min,2017-02-18 00:06:17,0.000000,0.000000,0.000000,0.000000,...,1.000000,18.000000,0.000000,5.000000,0.000000
25%,2017-02-20 17:11:48.750000128,0.000000,0.000000,0.000000,0.000000,...,1.000000,18.000000,2.000000,14.000000,9.000000
50%,2017-02-20 19:12:58,1.000000,0.000000,1.000000,0.000000,...,2.000000,20.000000,4.000000,20.000000,17.000000
75%,2017-02-20 22:22:14.249999872,1.000000,1.000000,2.000000,1.000000,...,3.000000,22.000000,8.000000,26.000000,28.000000
max,2017-02-24 08:43:47,3.000000,3.000000,3.000000,3.000000,...,5.000000,63.000000,21.000000,35.000000,68.000000
std,NaN,0.926542,0.915724,0.982776,0.921971,...,1.061842,3.300897,4.713267,7.229243,13.467493

# Check Missing Values

Since we know that some questions in the questionnaire have the other option, we'll look into them first.

In [ ]:
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

highestleague      100.000000
League              13.755199
Degree              11.712715
SPIN_T               4.827689
GADE                 4.820261
accept               3.074866
SPIN13               1.388889
SPIN11               1.388889
SPIN17               1.299762
SPIN12               1.247772
SPIN5                1.232917
SPIN10               1.188354
SPIN4                1.180927
SPIN9                1.173500
SPIN14               1.158645
SPIN6                1.158645
SPIN2                1.143791
SPIN16               1.091800
SPIN15               1.091800
SPIN8                1.069519
SPIN3                1.039810
SPIN7                1.024955
SPIN1                0.920974
Birthplace_ISO3      0.898693
Residence_ISO3       0.816993
streams              0.742721
Work                 0.282234
Hours                0.222816
Narcissism           0.170826
Reference            0.111408
dtype: float64

## Check `highestleague` and `League`

- Findings
    - `highestleague` has all `NaN` values because `League` is being used for the same purpose as `highestleague`
    - Some missing values like `na`, `none` that we need to filter out

- TODO:
    1. Remove `highestleague` column
    2. Convert the missing values

In [ ]:
df[['League', 'highestleague']]

        League  highestleague
1          NaN            NaN
2          NaN            NaN
3          NaN            NaN
4          NaN            NaN
5          NaN            NaN
...        ...            ...
14246      NaN            NaN
14247      NaN            NaN
14248     Gold            NaN
14249      NaN            NaN
14250  Diamond            NaN

[13464 rows x 2 columns]

In [ ]:
df[df['League'].notnull()]['League'].unique()

array(['-', 'Gold', 'none', ..., 'Not ranked yet S5, Plat IV S4.',
       "Season 4: Diamond II Right now: Platinum I (haven't played much)",
       'AHGL'], dtype=object)

## Check other columns
- Findings
    - Looks like no unusual values for the most common and least common answers in the specified columns

- TODO
    - Convert common placeholders (e.g., ‘N/A’, ‘null’, ‘unknown’) to NaN to standardize missing values

In [ ]:
col_names = ['GADE', 'Hours', 'Playstyle', 'earnings', 'whyplay', 'streams', 'Birthplace_ISO3', 'Residence_ISO3']

for column in col_names:
    print(f"Value counts for {column}:")
    print(df[column].value_counts(dropna=False).head(10))  # Display top 10 to spot odd entries
    print("\n")

Value counts for GADE:
GADE
Not difficult at all    6236
Somewhat difficult      5148
Very difficult          1012
NaN                      649
Extremely difficult      419
Name: count, dtype: int64


Value counts for Hours:
Hours
20.0    2293
10.0    1375
30.0    1186
15.0    1115
25.0     831
40.0     598
14.0     549
12.0     492
35.0     468
21.0     434
Name: count, dtype: int64


Value counts for Playstyle:
Playstyle
Multiplayer - online - with real life friends                    5564
Multiplayer - online - with strangers                            4134
Multiplayer - online - with online acquaintances or teammates    2652
Singleplayer                                                      762
Multiplayer - offline (people in the same room)                    48
all of the above                                                    7
All of the above                                                    6
Depends                                                             1
Multiplayer-online-real life friends and online acquaintances       1
Equal mix of real life friends and online                           1
Name: count, dtype: int64


Value counts for earnings:
earnings
I play for fun                                                                               12112
I play mostly for fun but earn a little on the side (tournament winnings, streaming, etc)      990
I earn a living by playing this game                                                            48
I play to win                                                                                    3
i try                                                                                            2
I play but don't have fun...                                                                     1
Fun and routine                                                                                  1
I don't earn jack ****                                                                           1
I play for relaxation and it gives me a few minutes to release everything                        1
making money from boosting,but mostly fun                                                        1
Name: count, dtype: int64


Value counts for whyplay:
whyplay
having fun                  5289
improving                   4927
winning                     2091
relaxing                     654
All of the above              26
all of the above              22
Improving and having fun      10
improving and having fun       8
winning and improving          6
having fun and improving       5
Name: count, dtype: int64


Value counts for streams:
streams
10.0    2181
5.0     1670
20.0    1182
2.0      990
15.0     953
3.0      832
0.0      826
4.0      714
8.0      576
1.0      510
Name: count, dtype: int64


Value counts for Birthplace_ISO3:
Birthplace_ISO3
USA    4261
DEU    1376
GBR     940
CAN     842
NLD     503
FRA     411
SWE     364
POL     281
BRA     260
PRT     241
Name: count, dtype: int64


Value counts for Residence_ISO3:
Residence_ISO3
USA    4569
DEU    1413
GBR    1032
CAN     994
NLD     506
FRA     391
SWE     379
DNK     254
BRA     253
AUS     245
Name: count, dtype: int64

In [ ]:
for column in col_names:
    print(f"Value counts for {column}:")
    print(df[column].value_counts(dropna=False).tail(10))  # Display top 10 to spot odd entries
    print("\n")

Value counts for GADE:
GADE
Not difficult at all    6236
Somewhat difficult      5148
Very difficult          1012
NaN                      649
Extremely difficult      419
Name: count, dtype: int64


Value counts for Hours:
Hours
420.0    1
160.0    1
69.0     1
33.0     1
46.0     1
57.0     1
85.0     1
67.0     1
87.0     1
150.0    1
Name: count, dtype: int64


Value counts for Playstyle:
Playstyle
Singleplayer is my favorite, but mostly play with real life friends                                                     1
i play a lot of ranked with strangers, but also play a lot with my IRL friends in normal games... so its kinda 50/50    1
Multiplayer with Friends and Strangers                                                                                  1
All multiplayer options listed above.                                                                                   1
With RL friends and randoms                                                                                             1
Online with friends, both real life friends and friends I've made online.                                               1
Multiplayer - online - with strangers against A.I.                                                                      1
Multiplayer equally with strangers or real life friends                                                                 1
with friend and stragers in same team                                                                                   1
I usually play online with my real life friends and the internet ones alike.                                            1
Name: count, dtype: int64


Value counts for earnings:
earnings
I play for fun, but also trying to get good at the game                               1
i would love to make money by playing some day                                        1
Make some money on the side betting on pro matches of the games I play                1
I play hoping one day I can be good enough to make a living out of it                 1
It is an escape and only thing I can do with my life at the moment.                   1
I play for fun, but if there's an opportunity to earn some money, I would love to.    1
Keep in touch w/ friends                                                              1
I Play for fun and working on making earn out of it.                                  1
I play ranked mostly                                                                  1
Strive to be Pro                                                                      1
Name: count, dtype: int64


Value counts for whyplay:
whyplay
i have fun when i see myself getting better at the game                                                                                                                                                                             1
Not feeling the pain my mind can inflict on me                                                                                                                                                                                      1
occupation                                                                                                                                                                                                                          1
Improving, relaxing and having fun are equally important to me and tied so close, that they cannot exist without each other (e.g. I can only have fun while relaxing and I always try to improve while relaxing and having fun),    1
All of above                                                                                                                                                                                                                        1
Making my brain go numb                                                                                                                                                                                                             1
Combination: Winning / Having fun                                                                                                                                                                                                   1
Improving + Fun                                                                                                                                                                                                                     1
to be occupied                                                                                                                                                                                                                      1
Mental priority is Fun>Improve>Win, actual priority once in game Win>Improve>Fun                                                                                                                                                    1
Name: count, dtype: int64


Value counts for streams:
streams
110.0     1
9001.0    1
61.0      1
140.0     1
72.0      1
168.0     1
44.0      1
36.0      1
41.0      1
54.0      1
Name: count, dtype: int64


Value counts for Birthplace_ISO3:
Birthplace_ISO3
VCT    1
GIB    1
BRN    1
KGZ    1
CUW    1
TKM    1
LIE    1
BLZ    1
MDV    1
MAC    1
Name: count, dtype: int64


Value counts for Residence_ISO3:
Residence_ISO3
VCT    1
MDA    1
BOL    1
GLP    1
NAM    1
JAM    1
LIE    1
IDN    1
KAZ    1
PSE    1
Name: count, dtype: int64